### ISSUE TITLE
Data not being loaded into ElasticSearch

### ISSUE THREAD

**Issue by apaytuvi** [cmdcolin/jbrowse_elasticsearch#5]
Hi,

I have a GFF file and I'm following these steps below to make the data available:

```
flatfile-to-json.pl --nameAttributes ID,description --gff file.gff3 --trackLabel ann
generate-elastic-search.pl --tracks ann
```

But when I search for instance `kinase` in the ElasticSearch track in JBrowse, the number of results is 0. What should I check?

Thanks.

**Comment by cmdcolin** [comment]
Hmm. If you have any more details I'd be interested to know

One thing you might try is database dump for elasticsearch, see https://github.com/elsiklab/jbrowse_elasticsearch/blob/master/docs/NOTES.md

**Comment by cmdcolin** [comment]
The problem that I think I am seeing is that the description is added to the "mRNA" features in the GFF, but if you loaded the track at the gene level, then --nameAttributes only includes attributes at the gene level (and since none exist, you just get gene IDs)

To remedy you can create a track loaded at the mRNA level with the --type flag e.g.


bin/flatfile-to-json.pl --gff myfile.gff --nameAttributes ID,description --type mRNA  --trackLabel dummytrack


Then delete elasticsearch existing database and re-run the generate-elastic-search indexing. Alternatively load the descriptions at the gene level.

I don't know if there's a better way to load the descriptions from subfeatures at the moment but I added a note to the README about this particular one

**Comment by cmdcolin** [comment]
Closed for now but let me know if there are any more issues :)!
