### ISSUE TITLE
using this plugin in genome apollo

### ISSUE THREAD

**Issue by michaelp896** [cmdcolin/jbrowse_elasticsearch#7]
Hi, can I use this search plugin with genome apollo? How would I go about implementing it? Running apollo from the gmod/docker-apollo container with an nginx reverse proxy

**Comment by cmdcolin** [comment]
It probably helps to get a full picture of what goes on in this plugin


Here are the components


1) Elasticsearch itself is a server that runs on a specified port, typically 9200. You do not expose this server to the outside world. It must be alive while you are indexing data and to perform any searching.

2) The "middleware" server, provided by this component, which runs on port 3000, which takes requests, passes them to the elasticsearch server, and then returns them. This is exposed to the outside world.

3) The bin/generate-elastic-search.pl script. This actually uses the same "machinery" as normal bin/generate-names.pl but instead loads the data into elastic search. It is not a server, it just runs once and loads the data into the elasticsearch server.

4) There is the JBrowse plugin which adds some simple dialog boxes to the menubar and sends requests to the middleware


I don't see why any of these things couldn't be used with webapollo, but it could be useful to understand how all these components work so that you can deploy it correctly in an apollo configuration. If you have any questions let me know

**Comment by cmdcolin** [comment]
I think it was decided that the issue with this was a apollo plugin loading thing or specifying plugins in multiple places (which is not disallowed but causes problems)

Will close for now, feel free to reopen if interested

**Comment by mictadlo** [comment]
Hi @michaelp896,
Did you get this plugin running with Apollo?

Michal
